### ISSUE TITLE
There's a lot of repetitive code 

### ISSUE THREAD

**Issue by shiryz** [WebAhead8/snakes-and-ladders#5]
https://github.com/WebAhead8/snakes-and-ladders/blob/main/scetch.js#L104

These same 6 lines of code are repeated throughout the function 

Try to think of a way that can help you abstract them

**Comment by shiryz** [comment]
Same here https://github.com/WebAhead8/snakes-and-ladders/blob/main/scetch.js#L107-L112

These 3 lines can be a function

**Comment by AladdinHammodi** [comment]
this function is used to draw ladders and snakes on the canvas 
that's why we repeated it 10 times because we have 5 ladders and 5 snakes
you can see that the drawing images in different positions.
i think your idea is to make a call back function, i think its a better way to write the code and will try to fix it

**Comment by AladdinHammodi** [comment]
this issue was fixed
all the repetitive code was replaced by a function
